use_frameworks!

target 'DZViewControllerLifeCircleAction_Example' do
  pod 'DZViewControllerLifeCircleAction', :path => '../'
  pod 'DZActivityBar'
  pod 'DZGeometryTools'
  pod 'DZURLRoute'

  target 'DZViewControllerLifeCircleAction_Tests' do
    inherit! :search_paths

    
  end
end
